abstract: Serve data in a round robin manner.
author: Kang-min Liu <gugod@gugod.org>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: Data-RoundRobin
no_index: 
  directory: 
    - inc
    - t
requires: 
  perl: 5.6.1
version: 0.03
